services:  
  webapp:
    container_name: webapp
    build: 
      dockerfile: Dockerfile
      context: .
    command: sh -c "cd /app/webapp && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"